name: syndatax-database

services:
  postgres:
    image: postgres:16-alpine
    container_name: syndatax_postgres
    restart: always
    environment:
      POSTGRES_DB: syndatax
      POSTGRES_USER: syndatax
      POSTGRES_PASSWORD: syndatax
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U syndatax -d syndatax"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
